package com.petstore.order.dto;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Metric detailing revenue, unit sales, and market share for a pet category.
 *
 * @param categoryId category identifier (e.g., "FISH", "DOGS")
 * @param categoryName human-readable category name
 * @param totalRevenue total revenue generated by this category
 * @param unitsSold total physical units purchased
 * @param orderCount number of orders containing items from this category
 * @param percentageShare percentage of total revenue across all categories
 */
public record CategorySalesMetric(
    String categoryId,
    String categoryName,
    BigDecimal totalRevenue,
    long unitsSold,
    long orderCount,
    double percentageShare
) implements Serializable {}
