# OpenEJB / TomEE Application Scoping Configuration
openejb.deploymentId.format = {appId}/{moduleId}/{ejbName}
openejb.jndiname.format = {appId}/{moduleId}/{ejbName}
openejb.classloader.force-ear-classloader = true
openejb.ear.single-classloader = true

# Intra-VM Local Reference Sharing
openejb.localcopy = true
openejb.check.local = false
openejb.strict.interface.declaration = false

# MDB Activation Destinations
opc/opc-ejb/PurchaseOrderMDB.activation.destination = jms/opc/OrderQueue
opc/opc-ejb/PurchaseOrderMDB.activation.destinationType = javax.jms.Queue
opc/opc-ejb/OrderApprovalMDB.activation.destination = jms/opc/OrderApprovalQueue
opc/opc-ejb/OrderApprovalMDB.activation.destinationType = javax.jms.Queue
opc/opc-ejb/InvoiceMDB.activation.destination = jms/opc/InvoiceTopic
opc/opc-ejb/InvoiceMDB.activation.destinationType = javax.jms.Topic
supplier/supplier-ejb/SupplierOrderMDB.activation.destination = jms/supplier/PurchaseOrderQueue
supplier/supplier-ejb/SupplierOrderMDB.activation.destinationType = javax.jms.Queue
