# OpenEJB / TomEE Application Scoping Configuration
openejb.deploymentId.format = {appId}/{moduleId}/{ejbName}
openejb.jndiname.format = {appId}/{moduleId}/{ejbName}
openejb.classloader.force-ear-classloader = true
openejb.ear.single-classloader = true

# Intra-VM Local Reference Sharing
openejb.localcopy = true
openejb.check.local = false
openejb.strict.interface.declaration = false
