spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongo:27017/petstore?replicaSet=rs0}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:29092}

legacy:
  datasource:
    url: ${LEGACY_DB_URL:jdbc:hsqldb:hsql://petstore-baseline:8088/petstore}

logging:
  level:
    root: WARN
    com.petstore: INFO
