CREATE TABLE CATEGORY (
  CATID VARCHAR(10) NOT NULL PRIMARY KEY
);

CREATE TABLE CATEGORY_DETAILS (
  CATID VARCHAR(10) NOT NULL,
  LOCALE VARCHAR(10) NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  IMAGE VARCHAR(255),
  DESCN VARCHAR(255),
  PRIMARY KEY (CATID, LOCALE)
);

CREATE TABLE PRODUCT (
  PRODUCTID VARCHAR(10) NOT NULL PRIMARY KEY,
  CATID VARCHAR(10) NOT NULL
);

CREATE TABLE PRODUCT_DETAILS (
  PRODUCTID VARCHAR(10) NOT NULL,
  LOCALE VARCHAR(10) NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  IMAGE VARCHAR(255),
  DESCN VARCHAR(255),
  PRIMARY KEY (PRODUCTID, LOCALE)
);

CREATE TABLE ITEM (
  ITEMID VARCHAR(10) NOT NULL PRIMARY KEY,
  PRODUCTID VARCHAR(10) NOT NULL
);

CREATE TABLE ITEM_DETAILS (
  ITEMID VARCHAR(10) NOT NULL,
  LOCALE VARCHAR(10) NOT NULL,
  LISTPRICE DECIMAL(10,2) NOT NULL,
  UNITCOST DECIMAL(10,2) NOT NULL,
  IMAGE VARCHAR(255),
  DESCN VARCHAR(255),
  ATTR1 VARCHAR(80),
  PRIMARY KEY (ITEMID, LOCALE)
);

CREATE TABLE INVENTORY (
  ITEMID VARCHAR(10) NOT NULL PRIMARY KEY,
  QUANTITY INTEGER NOT NULL
);

INSERT INTO CATEGORY VALUES ('FISH');
INSERT INTO CATEGORY_DETAILS VALUES ('FISH', 'en_US', 'Fish', 'fish.gif', 'Freshwater and saltwater fish');
INSERT INTO CATEGORY_DETAILS VALUES ('FISH', 'ja_JP', '魚', 'fish.gif', '熱帯魚と海水魚');

INSERT INTO PRODUCT VALUES ('FI-SW-01', 'FISH');
INSERT INTO PRODUCT_DETAILS VALUES ('FI-SW-01', 'en_US', 'Angelfish', 'fish1.gif', 'Saltwater fish');

INSERT INTO ITEM VALUES ('EST-1', 'FI-SW-01');
INSERT INTO ITEM_DETAILS VALUES ('EST-1', 'en_US', 16.50, 10.00, 'fish1.gif', 'Saltwater fish', 'Large');
INSERT INTO INVENTORY VALUES ('EST-1', 150);
