CREATE TABLE CATEGORY (
  CATID VARCHAR(10) NOT NULL PRIMARY KEY
);

CREATE TABLE CATEGORY_DETAILS (
  CATID VARCHAR(10) NOT NULL,
  LOCALE VARCHAR(10) NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  IMAGE VARCHAR(255),
  DESCN VARCHAR(255),
  PRIMARY KEY (CATID, LOCALE)
);

CREATE TABLE PRODUCT (
  PRODUCTID VARCHAR(10) NOT NULL PRIMARY KEY,
  CATID VARCHAR(10) NOT NULL
);

CREATE TABLE PRODUCT_DETAILS (
  PRODUCTID VARCHAR(10) NOT NULL,
  LOCALE VARCHAR(10) NOT NULL,
  NAME VARCHAR(80) NOT NULL,
  IMAGE VARCHAR(255),
  DESCN VARCHAR(255),
  PRIMARY KEY (PRODUCTID, LOCALE)
);

CREATE TABLE ITEM (
  ITEMID VARCHAR(10) NOT NULL PRIMARY KEY,
  PRODUCTID VARCHAR(10) NOT NULL
);

CREATE TABLE ITEM_DETAILS (
  ITEMID VARCHAR(10) NOT NULL,
  LOCALE VARCHAR(10) NOT NULL,
  LISTPRICE DECIMAL(10,2) NOT NULL,
  UNITCOST DECIMAL(10,2) NOT NULL,
  IMAGE VARCHAR(255),
  DESCN VARCHAR(255),
  ATTR1 VARCHAR(80),
  PRIMARY KEY (ITEMID, LOCALE)
);

CREATE TABLE INVENTORY (
  ITEMID VARCHAR(10) NOT NULL PRIMARY KEY,
  QUANTITY INTEGER NOT NULL
);

INSERT INTO CATEGORY VALUES ('FISH');
INSERT INTO CATEGORY_DETAILS VALUES ('FISH', 'en_US', 'Fish', 'fish.gif', 'Freshwater and saltwater fish');
INSERT INTO CATEGORY_DETAILS VALUES ('FISH', 'ja_JP', '魚', 'fish.gif', '熱帯魚と海水魚');

INSERT INTO PRODUCT VALUES ('FI-SW-01', 'FISH');
INSERT INTO PRODUCT_DETAILS VALUES ('FI-SW-01', 'en_US', 'Angelfish', 'fish1.gif', 'Saltwater fish');

INSERT INTO ITEM VALUES ('EST-1', 'FI-SW-01');
INSERT INTO ITEM_DETAILS VALUES ('EST-1', 'en_US', 16.50, 10.00, 'fish1.gif', 'Saltwater fish', 'Large');
INSERT INTO INVENTORY VALUES ('EST-1', 150);

CREATE TABLE PURCHASEORDER (
  POID VARCHAR(255) NOT NULL PRIMARY KEY,
  PODATE BIGINT,
  POEMAILID VARCHAR(255),
  POLOCALE VARCHAR(255),
  POUSERID VARCHAR(255),
  POVALUE DOUBLE,
  CONTACTINFO_OPENEJB_PK BIGINT,
  CREDITCARD_OPENEJB_PK BIGINT
);

CREATE TABLE MANAGER (
  ORDERID VARCHAR(255) NOT NULL PRIMARY KEY,
  STATUS VARCHAR(255)
);

CREATE TABLE LINEITEM (
  OPENEJB_PK BIGINT NOT NULL PRIMARY KEY,
  CATEGORYID VARCHAR(255),
  ITEMID VARCHAR(255),
  LINENUMBER VARCHAR(255),
  PRODUCTID VARCHAR(255),
  QUANTITY INTEGER,
  QUANTITYSHIPPED INTEGER,
  UNITPRICE DOUBLE,
  SUPPLIERORDER_LINEITEMS_POID VARCHAR(255),
  PURCHASEORDER_LINEITEMS_POID VARCHAR(255)
);

CREATE TABLE CONTACTINFO (
  OPENEJB_PK BIGINT NOT NULL PRIMARY KEY,
  EMAIL VARCHAR(255),
  FAMILYNAME VARCHAR(255),
  GIVENNAME VARCHAR(255),
  TELEPHONE VARCHAR(255),
  ADDRESS_OPENEJB_PK BIGINT
);

CREATE TABLE ADDRESS (
  OPENEJB_PK BIGINT NOT NULL PRIMARY KEY,
  CITY VARCHAR(255),
  COUNTRY VARCHAR(255),
  STATE VARCHAR(255),
  STREETNAME1 VARCHAR(255),
  STREETNAME2 VARCHAR(255),
  ZIPCODE VARCHAR(255)
);

CREATE TABLE CREDITCARD (
  OPENEJB_PK BIGINT NOT NULL PRIMARY KEY,
  CARDNUMBER VARCHAR(255),
  CARDTYPE VARCHAR(255),
  EXPIRYDATE VARCHAR(255)
);

INSERT INTO ADDRESS VALUES (101, 'Santa Clara', 'USA', 'CA', '123 Sun Way', NULL, '95054');
INSERT INTO CONTACTINFO VALUES (201, 'duke@sun.com', 'Java', 'Duke', '408-555-1212', 101);
INSERT INTO CREDITCARD VALUES (301, '1111222233334444', 'Visa', '12/2028');

INSERT INTO PURCHASEORDER VALUES ('100115', 1788534995811, 'duke@sun.com', 'en_US', 'j2ee', 38.50, 201, 301);
INSERT INTO MANAGER VALUES ('100115', 'PENDING');

INSERT INTO LINEITEM VALUES (1, 'FISH', 'EST-1', '0', 'FI-SW-01', 2, 0, 16.50, NULL, '100115');
INSERT INTO LINEITEM VALUES (2, 'FISH', 'EST-2', '1', 'FI-SW-01', 1, 0, 5.50, NULL, '100115');

